Algoritmo "HELLOWORD"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2023
Var
// Seção de Declarações das variáveis 
     C: CARACTERE

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   C<-("OLÁ, MUNDO!")
   ESCREVA (C, " BEM VINDO!")
   
Fimalgoritmo