Algoritmo "CONTDEZ"

Var
   CONTADOR: INTEIRO


Inicio
    ESCREVAL("=====================")
    ESCREVAL("CONTADOR DE NÚMEROS")
    ESCREVAL("=====================")
    
    ESCREVAL("VAMOS CONTAR DE 0 A 10")
    ENQUANTO (CONTADOR <= 10) FACA
    ESCREVAL(CONTADOR)
    CONTADOR <-(CONTADOR + 1)
    FIMENQUANTO
    ESCREVAL()
    ESCREVAL("TERMINAMOS DE CONTAR")


Fimalgoritmo