Algoritmo "MELHOR-ALUNO"

Var
   AN , TURMA: INTEIRO
   NT : REAL
   N  : CARACTERE


Inicio
      ESCREVAL("================")
      ESCREVAL("COLÉGIO PÓDIO")
      ESCREVAL("================")

      ESCREVAL("Quantos alunos a turma tem?")
      LEIA(AN)
      
      ENQUANTO (TURMA <= AN) FACA
      ESCREVAL("Aluno ",turma)
      ESCREVAL("Nome: ")
      LEIA(N)
      ESCREVAL("Nota: ")
      LEIA(NT)
      
      FIMENQUANTO
Fimalgoritmo